### PR TITLE
Add mail attachments 191204

### PR DESCRIPTION
**Pull request by Atastor**
I am not quite sure anymore, why I didn't submit a pull request in February ...

It is useful for me and works in my app, and judging from the small number of changes, there should not be too much danger in merging this.

Regards
Michael

### CODE REVIEW

**Comment by wndxlori** [comment]
This looks great, Michael, thanks.  I would like to see the spec for mail updated to include a test for attachments as well?

And I'll see about getting the travis.yml file updated for the new-and-improved build process so we can actually depend on the build checks again.

**Comment by Atastor** [comment]
> This looks great, Michael, thanks. I would like to see the spec for mail updated to include a test for attachments as well?

Ok :-)

**Comment by Atastor** [comment]
Hmm, the spec seems to run, but having to view the logs via the console muddys the water a bit... Also apparently a bundle update slipped into the pull request.

Should I delete this and start a new one?

**Comment by wndxlori** [comment]
Although I'm generally not a fan of force-push, if you want to 1) remove that last commit 2) redo without the bundle update, I'd be fine with that. This exact problem, btw, is why I almost always code-review my own commits. So I don't accidentally commit something I didn't intend. Which I have totally done in the past.

**Comment by Atastor** [comment]
Ok, I promise to be better in future.
I close this pr and open a new one (#503) with a "better" set of changes.

**Pull request closed without merging**
