### PR TITLE
[iOS] Add Device.force_touch?

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by markrickert** [comment]
Nice! I'm wondering if tests for this would be of any benefit?

**Comment by hboon** [comment]
Do you mean test as in a spec for this or whether this is useful? For the former, I'm not sure how to write one, other than verifying that it's false (because it's in the simulator)?

**Comment by markrickert** [comment]
Oh, i definitely think it's useful... but tests can run on the device as well. The test should probably check to see what device it is and if it's a 6s or a 6s Plus, it should return `true`.

**Comment by hboon** [comment]
Ah, OK.

I usually use this: https://gist.github.com/hboon/e22943f155cc628c782d. I don't think -moHardwareString can be translated to RubyMotion though. Any idea how to check for device type otherwise?

**Comment by hboon** [comment]
I want to get this in patch in because I'm already using it :) Anyone have any idea how to write a test for this? Ping @clayallsopp @colinta for help.

(The Travis failure looks unrelated).

**Comment by colinta** [comment]
Cool! I'm until the sim adds support, we can't test it. I'll take a look and merge soon.

**Comment by hboon** [comment]
@colinta did you have a chance to look at this? Want to get rid of my private fork :)

**Comment by colinta** [comment]
Ah yes, thank's for reminding me!  @markrickert I'm gonna punt on requiring specs, because those won't be picked up in automated testing.  If he's been using this code successfully this whole time than it's obviously working, that's good enough for me.

**Comment by hboon** [comment]
@colinta thanks!

**Comment by markrickert** [comment]
lol, no worries... I'm pretty sure it's not possible to automate the testing for this.

**Pull request merged**
